# Generated by Django 4.2.1 on 2023-06-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0002_post_alter_user_name_alter_user_password_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='post_photo/'),
        ),
    ]
