# Generated by Django 4.2.1 on 2023-06-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0005_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user_photos/'),
        ),
    ]
