# Generated by Django 4.2.1 on 2023-07-15 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gramm', '0007_like_person_id_alter_like_post_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
