# Generated by Django 4.2.1 on 2023-07-18 16:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0008_alter_like_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
